### ISSUE TITLE
Shift+Click should be used to select individual sources

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/tigger#37]
##### at 2012-06-04 16:10:13 Oleg Smirnov reported:

Shift+Click should be used to select individual sources

**Comment by razman786** [comment]
@gijzelaerr - v1.6.0 of tigger has CTRL+Click to select individual sources and SHIFT+Click to select multiple sources with a bounding box. The current mouse scheme fits the mouse reference help in the GUI and therefore assume this bug is now resolved. Closing this issue, please re-open it if I have misunderstood.
