### ISSUE TITLE
Tigger incompatible with pyfits>=3.4

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/tigger#71]
Tigger uses `header.update(key, value, comment)` to update FITS headers. This has been deprecated, the new way is `header[key] = (value, comment)`. This used to raise a warning, but it raises an error in pyfits versions >= 3.4

@gijzelaerr note that kernsuite tigger crashes because of this.

**Comment by ArunAniyan** [comment]
So the error which I too get is associated with this ?
Tigger 1.3.4 (ubuntu 16.04)  gives me this error whenever I try to load a fits file (which other image viewers load normally)

Error loading FITS image 1466813419_1284.hh_vv.ms_1-7_fixed.ms_I_3deg_pself1.image.fits: 'Header' object has no attribute 'ascard'. This may be due to a bug in Tigger; if the FITS file loads fine in another viewer, please send the FITS file, along with a copy of any error messages from the text console, to osmirnov@gmail.com.

The traceback on the terminal shows this

File "/usr/lib/python2.7/dist-packages/Tigger/Images/Manager.py", line 128, in loadImage
image = SkyImage.FITSImagePlotItem(str(filename));
File "/usr/lib/python2.7/dist-packages/Tigger/Images/SkyImage.py", line 553, in init
self.read(filename,hdu);
File "/usr/lib/python2.7/dist-packages/Tigger/Images/SkyImage.py", line 581, in read
hdr1 = pyfits.Header(filter(lambda x:not str(x).startswith('HISTORY'),hdr.ascard));
AttributeError: 'Header' object has no attribute 'ascard'

**Comment by o-smirnov** [comment]
Definitely associated with ``pyfits`` changing its API. Naughty naughty.

**Comment by gijzelaerr** [comment]
hm, I thought `pyfits` itself was deprecated and replaced with `astropy.io.fits`

**Comment by SpheMakh** [comment]
@gijzelaerr It is, but I think pyfits is aliased as astropy.io.fits. In any case, tigger is incompatible with versions >=3.4.

**Comment by gijzelaerr** [comment]
probably not very hard to fix

http://docs.astropy.org/en/stable/io/fits/api/headers.html#astropy.io.fits.Header.ascard

**Comment by bmerry** [comment]
I'm also running into this having switched SDP's containers to Ubuntu 16.04 and KERN-1.

I'm prepared to look through the code to change all the calls to `update` into dictionary assignment, provided that nobody is going to object to pre-3.1 versions of pyfits no longer working, and somebody can volunteer to test the changes to ensure I didn't break anything (I'm only using it for tigger-convert at the moment, so I could easily break something and not notice). Pyfits 3.1 was released 2012-08, so it won't be in Ubuntu 12.04 which is a maintained LTS release.

By the way, I don't see pyfits listed in the requirements of setup.py, even though tigger (the script) seems to load it unconditionally.

**Comment by bmerry** [comment]
Never mind, I see @sjperkins has already made a pull request. Is it getting any love?

**Comment by sjperkins** [comment]
@bmerry I'm running https://github.com/ska-sa/tigger/pull/73 on my 16.04 laptop. You'll also probably run into https://github.com/ska-sa/tigger/issues/74 which I solve by commenting out the offending code and hardcoding ``__version__ = 'devel'``.

**Comment by gijzelaerr** [comment]
ok, guys i'll have a look at the pull requests this week or next week.
